# One convenient command to type instead of 3 commands -- Yan 10/29
# "sh make.sh" or "sh ma[TAB]"

make clean
make dep

clear # clear the screen so we can see the compile warning (generated by below command) better

sudo make